services:
  db:
    image: mysql:8.0
    container_name: demetra_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./demetra.sql:/docker-entrypoint-demetra.d/demetra.sql

  server:
    image: node:18
    container_name: demetra_server
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && if [ \"$NODE_ENV\" = 'production' ]; then npm run start:prod; else npm start; fi"
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      NODE_ENV: ${NODE_ENV}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DIALECT: ${DB_DIALECT}

volumes:
  db_data: